# Generated by Django 3.2.13 on 2022-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_rename_username_userdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
