# Generated by Django 3.2.13 on 2022-05-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('Book_id', models.CharField(max_length=100, unique=True)),
                ('Buyer_id', models.CharField(max_length=100)),
                ('seller_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.CharField(max_length=10)),
                ('delivery_address', models.CharField(max_length=1000)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
