# Generated by Django 3.2.13 on 2022-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='payment_status',
            field=models.CharField(max_length=10),
        ),
    ]
